// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2pFESW1N3A4gCTB3OWv5OlcTCSWNnx4',
    appId: '1:143206628546:web:87f0cc2348a2e2300ecf5b',
    messagingSenderId: '143206628546',
    projectId: 'newp-7b77b',
    authDomain: 'newp-7b77b.firebaseapp.com',
    databaseURL: 'https://newp-7b77b-default-rtdb.firebaseio.com',
    storageBucket: 'newp-7b77b.appspot.com',
    measurementId: 'G-59187Y8EM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZkULTWeMHOr8PadmPkaWC2RiQGbIkgo',
    appId: '1:143206628546:android:6e9bf254233f58cc0ecf5b',
    messagingSenderId: '143206628546',
    projectId: 'newp-7b77b',
    databaseURL: 'https://newp-7b77b-default-rtdb.firebaseio.com',
    storageBucket: 'newp-7b77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZMuz1cRwvFTvSGYwE-GG-TGwy3plgks',
    appId: '1:143206628546:ios:45d93a3750484b180ecf5b',
    messagingSenderId: '143206628546',
    projectId: 'newp-7b77b',
    databaseURL: 'https://newp-7b77b-default-rtdb.firebaseio.com',
    storageBucket: 'newp-7b77b.appspot.com',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZMuz1cRwvFTvSGYwE-GG-TGwy3plgks',
    appId: '1:143206628546:ios:45d93a3750484b180ecf5b',
    messagingSenderId: '143206628546',
    projectId: 'newp-7b77b',
    databaseURL: 'https://newp-7b77b-default-rtdb.firebaseio.com',
    storageBucket: 'newp-7b77b.appspot.com',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu2pFESW1N3A4gCTB3OWv5OlcTCSWNnx4',
    appId: '1:143206628546:web:8f09e82914cca5740ecf5b',
    messagingSenderId: '143206628546',
    projectId: 'newp-7b77b',
    authDomain: 'newp-7b77b.firebaseapp.com',
    databaseURL: 'https://newp-7b77b-default-rtdb.firebaseio.com',
    storageBucket: 'newp-7b77b.appspot.com',
    measurementId: 'G-LGJVCZYS3M',
  );

}