// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKdv2BIA1RF66qS9eKbX-e7i9axcJL9P8',
    appId: '1:910230325944:web:6bd416c00582340b8c024d',
    messagingSenderId: '910230325944',
    projectId: 'etsfyp',
    authDomain: 'etsfyp.firebaseapp.com',
    databaseURL: 'https://etsfyp-default-rtdb.firebaseio.com',
    storageBucket: 'etsfyp.appspot.com',
    measurementId: 'G-CFBGWHP04M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-pHAJmBxKey82MGy6BFXTxjEpfTOTnbE',
    appId: '1:910230325944:android:69617722b723710c8c024d',
    messagingSenderId: '910230325944',
    projectId: 'etsfyp',
    databaseURL: 'https://etsfyp-default-rtdb.firebaseio.com',
    storageBucket: 'etsfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvboLPf3bF4-PpOlMtqvFP18NJZDt9cRc',
    appId: '1:910230325944:ios:4125dd54aba0c80a8c024d',
    messagingSenderId: '910230325944',
    projectId: 'etsfyp',
    databaseURL: 'https://etsfyp-default-rtdb.firebaseio.com',
    storageBucket: 'etsfyp.appspot.com',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvboLPf3bF4-PpOlMtqvFP18NJZDt9cRc',
    appId: '1:910230325944:ios:4125dd54aba0c80a8c024d',
    messagingSenderId: '910230325944',
    projectId: 'etsfyp',
    databaseURL: 'https://etsfyp-default-rtdb.firebaseio.com',
    storageBucket: 'etsfyp.appspot.com',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKdv2BIA1RF66qS9eKbX-e7i9axcJL9P8',
    appId: '1:910230325944:web:fd39027d5867d8d78c024d',
    messagingSenderId: '910230325944',
    projectId: 'etsfyp',
    authDomain: 'etsfyp.firebaseapp.com',
    databaseURL: 'https://etsfyp-default-rtdb.firebaseio.com',
    storageBucket: 'etsfyp.appspot.com',
    measurementId: 'G-Z4JQYF67CB',
  );

}