// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCpqV9xUCWulQ7VokDDkBMb5gIZlVwCk',
    appId: '1:66699206284:web:91e60b2168da1bb61ae5a9',
    messagingSenderId: '66699206284',
    projectId: 'maryam-15bce',
    authDomain: 'maryam-15bce.firebaseapp.com',
    databaseURL: 'https://maryam-15bce-default-rtdb.firebaseio.com',
    storageBucket: 'maryam-15bce.appspot.com',
    measurementId: 'G-JR4Q8FSKZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZRF48Av2CNhH0DqVtdCUPrW24Cqr5NNk',
    appId: '1:66699206284:android:7a8d0554a5a9a90f1ae5a9',
    messagingSenderId: '66699206284',
    projectId: 'maryam-15bce',
    databaseURL: 'https://maryam-15bce-default-rtdb.firebaseio.com',
    storageBucket: 'maryam-15bce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGV0LMW6jAR7U-6U52DnXXdTY9lHa9vjo',
    appId: '1:66699206284:ios:6b3e943e304308cb1ae5a9',
    messagingSenderId: '66699206284',
    projectId: 'maryam-15bce',
    databaseURL: 'https://maryam-15bce-default-rtdb.firebaseio.com',
    storageBucket: 'maryam-15bce.appspot.com',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGV0LMW6jAR7U-6U52DnXXdTY9lHa9vjo',
    appId: '1:66699206284:ios:6b3e943e304308cb1ae5a9',
    messagingSenderId: '66699206284',
    projectId: 'maryam-15bce',
    databaseURL: 'https://maryam-15bce-default-rtdb.firebaseio.com',
    storageBucket: 'maryam-15bce.appspot.com',
    iosBundleId: 'com.example.ironProjectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJCpqV9xUCWulQ7VokDDkBMb5gIZlVwCk',
    appId: '1:66699206284:web:84df02d61d3a3f5a1ae5a9',
    messagingSenderId: '66699206284',
    projectId: 'maryam-15bce',
    authDomain: 'maryam-15bce.firebaseapp.com',
    databaseURL: 'https://maryam-15bce-default-rtdb.firebaseio.com',
    storageBucket: 'maryam-15bce.appspot.com',
    measurementId: 'G-2WV7XTWZSD',
  );

}